### ISSUE TITLE
How we can change the map for an other country and embed it inside a website? please thank you

### ISSUE THREAD

**Issue by KalipheGTU** [bsouthga/d3-exploder#5]
How we can change the map for an other country and embed it inside a website? please thank you

**Comment by bsouthga** [comment]
Hi @KalipheGTU ! If you are new to making maps with D3, I would suggest taking a look at this article: https://bost.ocks.org/mike/map/

To answer your questions: 
- to use a different country, you'll need to find a `geojson` file containing the geographic information for that country. 
- To get a map on your website, you'll need to include the following three javascript files in the `<head>` element of your html.

```html
<script src="http://d3js.org/d3.v4.min.js" charset="utf-8"></script>
<script src="http://d3js.org/topojson.v2.min.js"></script>
<script src="d3-exploder.min.js"></script>
```

And then add your specific map code (like that in the article linked above).

Here is a JSFiddle using mexico instead of the US to get you started: https://jsfiddle.net/34vs145z/18/

**Comment by KalipheGTU** [comment]
thank you misterBousthga, i'll try it
Cheers
